// All UI text. Indonesian is the default language. A value is either a string
// with {placeholders}, a function of the params, or an array (tip lists).
// Every key should exist in both languages; missing keys fall back to English.

const id = {
  common: {
    loading: 'Memuat…',
    connecting: 'Menghubungkan…',
    close: 'Tutup',
    youParen: ' (kamu)',
    and: 'dan',
    offline: 'Koneksi terputus. Menghubungkan ulang…',
    yourTurn: 'Giliranmu',
    language: 'Bahasa',
  },
  role: {
    GOOD: { label: 'Pelayan Setia Arthur', short: 'Baik' },
    MERLIN: { label: 'Merlin', short: 'Merlin' },
    EVIL: { label: 'Antek Mordred', short: 'Jahat' },
    teamGood: 'Tim Baik',
    teamEvil: 'Tim Jahat',
    knowsMerlin: 'Para Antek Mordred adalah:',
    knowsEvil: 'Sesama Antek Mordred:',
    noFellows: 'Kamu tidak punya teman sesama Antek Mordred.',
    goal: {
      GOOD: 'Kamu tidak tahu peran siapa pun. Bantu Tim Baik menyukseskan 3 misi dan perhatikan siapa yang terus menggagalkannya.',
      MERLIN: 'Bimbing Tim Baik tanpa terlihat mencolok. Kalau Tim Jahat berhasil menebakmu di akhir, Tim Jahat menang.',
      EVIL: 'Masuk ke tim misi dan gagalkan 3 misi. Kalau Tim Baik menang 3 misi, timmu harus menebak Merlin.',
    },
  },
  login: {
    subtitle: 'The Resistance: Avalon. Ayo bergabung ke meja.',
    name: 'Namamu',
    password: 'Kata sandi permainan',
    join: 'Gabung',
    joining: 'Bergabung…',
    rejoinHint: 'Sesimu hilang di tengah permainan? Gabung lagi dengan nama yang sama persis untuk kembali ke kursimu.',
    hostPassword: 'Kata sandi host',
    hostSubmit: 'Masuk sebagai host',
  },
  game: {
    playingAs: 'Bermain sebagai {name}',
    leave: 'Keluar',
    leaveConfirm: 'Keluar dari lobi?',
    lobbyWaiting: 'Kamu sudah masuk! Menunggu host memulai permainan.',
    inLobby: 'Di lobi',
    waitingNewGame: 'Menunggu host memulai permainan baru.',
    help: 'Cara Bermain',
  },
  lobby: {
    needs: 'Avalon butuh 5 sampai 10 pemain.',
    rules: ({ n, good, evil, sizes }) =>
      `Dengan ${n} pemain: ${good} Tim Baik (termasuk Merlin) dan ${evil} Tim Jahat. Ukuran tim misi: ${sizes}`,
  },
  board: {
    label: 'Papan misi',
    q: 'M{n}',
    doubleFail: '★ Misi 4 butuh 2 kartu Gagal untuk gagal',
    rejects: 'Tim ditolak berturut-turut',
    rejectsOf: '{n} dari 5',
    leader: 'Pemimpin',
    questDone: '{s} sukses, {f} gagal',
    questSize: '{n} pemain',
  },
  players: {
    title: 'Pemain',
    online: 'Online',
    offline: 'Offline',
    leader: '♛ Pemimpin',
    onTeam: 'Ikut misi',
    voted: 'Sudah vote',
    voting: 'Sedang vote…',
    played: 'Sudah main',
    playing: 'Sedang main…',
    knownEvil: 'Jahat (kamu tahu)',
    kick: 'Keluarkan',
  },
  status: {
    leaderYou: 'Kamu pemimpinnya. Pilih {size} pemain untuk Misi {q}.',
    leaderOther: '{leader} sedang memilih {size} pemain untuk Misi {q}.',
    voteYou: 'Vote tim usulan {leader} untuk Misi {q}.',
    waitingVotes: 'Menunggu vote dari {names}.',
    questYou: 'Kamu ikut Misi {q}. Mainkan kartumu.',
    questOther: 'Misi {q} sedang berjalan. Menunggu {names}.',
    merlinEvil: 'Tim Baik sudah menang 3 misi! Diskusikan dengan timmu dan pilih siapa yang kamu kira Merlin.',
    merlinGood: 'Tim Baik sudah menang 3 misi! Tim Jahat sekarang mencoba menebak Merlin…',
    voteResult: 'Hasil voting diumumkan.',
    questResult: 'Hasil Misi {q} diumumkan.',
  },
  pick: {
    title: 'Pilih timmu',
    propose: 'Usulkan tim ini',
  },
  vote: {
    title: 'Tim usulan {leader} untuk Misi {q}',
    approve: 'Setuju',
    reject: 'Tolak',
    secret: 'Vote-mu rahasia sampai semua orang selesai vote.',
    youVoted: 'Kamu memilih {choice}. Kamu masih bisa menggantinya sampai vote terakhir masuk.',
    progress: '{done}/{total} sudah vote. Tim butuh lebih dari setengah suara untuk disetujui.',
    lastChance: 'Kalau tim ini ditolak, Tim Jahat menang!',
  },
  quest: {
    title: 'Tim Misi {q}',
    success: 'Sukses',
    fail: 'Gagal',
    evilHint: 'Kartumu anonim. Hanya totalnya yang diumumkan.',
    goodHint: 'Pelayan setia Arthur selalu memilih Sukses.',
    played: 'Kamu memilih {card}. Kartumu tidak bisa diganti.',
    progress: '{done}/{total} kartu sudah dimainkan.',
    needs2: 'Misi ini butuh 2 kartu Gagal untuk gagal.',
    needs1: 'Satu kartu Gagal sudah cukup untuk menggagalkan misi ini.',
  },
  merlin: {
    title: 'Tebak Merlin',
    unmask: 'Para Antek Mordred membuka kedok:',
    lock: 'Diskusikan dengan timmu. Tebakan terkunci saat {n} dari kalian memilih pemain yang sama.',
    votes: '{n} vote',
    goodHint: 'Kalau Tim Jahat menebak Merlin dengan benar, Tim Jahat menang. Kalau salah, Tim Baik menang.',
  },
  over: {
    good: 'Tim Baik menang!',
    evil: 'Tim Jahat menang!',
    ended: 'Permainan berakhir',
    roles: 'Peran semua pemain',
    guess: ' (tebakan Tim Jahat)',
  },
  reason: {
    '5_rejections': 'Lima usulan tim berturut-turut ditolak.',
    '3_quests_failed': 'Tiga misi gagal.',
    merlin_found: 'Tim Baik menyelesaikan 3 misi, tapi Tim Jahat berhasil menemukan Merlin ({guess}).',
    merlin_safe: 'Tim Baik menyelesaikan 3 misi. Tim Jahat menebak {guess}, padahal Merlin adalah {merlin}.',
    aborted: 'Host mengakhiri permainan lebih awal.',
  },
  results: {
    title: 'Hasil terakhir',
    quest: 'Misi {q}:',
    success: 'Sukses',
    failed: 'Gagal',
    counts: '{s} Sukses, {f} Gagal',
    proposal: 'Misi {q}, usulan ke-{attempt} oleh {leader}:',
    approved: 'Disetujui',
    rejected: 'Ditolak',
    team: 'Tim: {names}',
    history: 'Semua voting tim ({n})',
  },
  reveal: {
    voteTitle: 'Hasil Voting',
    questTitle: 'Hasil Misi',
    approved: 'Tim disetujui!',
    rejected: 'Tim ditolak!',
    count: '{yes} Setuju · {no} Tolak',
    proposedBy: 'Tim usulan {leader} untuk Misi {q}:',
    approvers: 'Setuju',
    rejecters: 'Tolak',
    nobody: 'Tidak ada',
    questOk: 'Misi {q} SUKSES!',
    questFail: 'Misi {q} GAGAL!',
    cards: '{s} kartu Sukses · {f} kartu Gagal',
    teamWas: 'Anggota tim misi:',
    score: 'Skor: Tim Baik {good} – Tim Jahat {evil}',
    nextQuest: 'Tim ini berangkat misi:',
    youOnQuest: 'Kamu ikut misi ini! Siapkan kartumu.',
    nextLeader: 'Pemimpin berikutnya:',
    youLead: 'Kamu pemimpin berikutnya! Siap-siap memilih tim.',
    rejectCount: 'Tim ditolak {n} kali berturut-turut (maks. 5).',
    lastReject: 'Satu penolakan lagi dan Tim Jahat menang!',
    merlin: 'Tim Baik sudah menang 3 misi! Tim Jahat sekarang akan menebak siapa Merlin.',
    end: {
      '5_rejections': 'Lima tim ditolak berturut-turut. Tim Jahat menang!',
      '3_quests_failed': 'Tiga misi gagal. Tim Jahat menang!',
    },
    countdown: 'Lanjut dalam {s} detik',
    skip: 'Lewati jeda',
  },
  roleCard: {
    tapToShow: 'Ketuk untuk melihat peran rahasiamu',
    yourRole: 'Peran rahasiamu',
    show: 'Lihat',
    hide: 'Sembunyikan',
  },
  roleReveal: {
    started: 'Permainan dimulai!',
    private: 'Pastikan tidak ada orang lain yang melihat layarmu.',
    show: 'Lihat peranku',
    youAre: 'Kamu adalah',
    tipsTitle: 'Cara memainkan peran ini',
    done: 'Saya mengerti, mulai main',
  },
  turn: {
    pick: 'Pilih tim',
    vote: 'Vote tim',
    quest: 'Mainkan kartu misi',
    merlin: 'Tebak Merlin',
    result: 'Lihat hasil',
  },
  modal: {
    pick: 'Pilih Tim',
    vote: 'Voting Tim',
    quest: 'Misi',
    merlin: 'Tebak Merlin',
  },
  tips: {
    title: '💡 Tips',
    hide: 'Sembunyikan tips',
    role: {
      GOOD: [
        'Kamu tidak tahu peran siapa pun, jadi andalkan pengamatan.',
        'Kalau misi gagal, berarti ada Tim Jahat di tim misi itu. Ingat siapa saja anggotanya.',
        'Perhatikan juga siapa yang menyetujui tim yang gagal.',
      ],
      MERLIN: [
        'Kamu tahu siapa saja Tim Jahat, tapi jangan sampai ketahuan.',
        'Arahkan teman secara halus, jangan menuduh terang-terangan.',
        'Kalau Tim Baik menang 3 misi, Tim Jahat boleh menebak siapa Merlin. Kalau tebakannya benar, Tim Baik kalah.',
      ],
      EVIL: [
        'Berpura-puralah jadi Tim Baik dan ikut berdiskusi seperti biasa.',
        'Bantu sesama Tim Jahat diam-diam, jangan terlihat terlalu kompak.',
        'Cari pemain yang selalu "kebetulan benar" soal siapa yang jahat, karena dia kemungkinan Merlin.',
      ],
    },
    leader: {
      GOOD: [
        'Masukkan dirimu sendiri, karena kamu yakin dirimu baik.',
        'Pilih pemain yang pernah ikut misi yang sukses.',
        'Hindari pemain yang pernah ikut misi yang gagal.',
      ],
      MERLIN: [
        'Masukkan dirimu sendiri dan pemain yang kamu tahu baik.',
        'Sesekali masukkan pemain yang belum jelas, supaya pilihanmu tidak terlihat terlalu "sempurna".',
        'Beri alasan yang masuk akal, misalnya "dia ikut misi yang sukses tadi."',
      ],
      EVIL: [
        'Masukkan dirimu atau satu teman Jahat. Satu saja sudah cukup untuk menggagalkan misi.',
        'Isi sisanya dengan pemain baik supaya timmu terlihat meyakinkan.',
        'Jangan memasukkan terlalu banyak Tim Jahat sekaligus, karena itu mencurigakan.',
      ],
    },
    vote: {
      GOOD: [
        'Setujui tim yang berisi pemain yang kamu percaya.',
        'Tolak tim yang berisi pemain yang mencurigakan.',
        'Kalau sudah 4 kali ditolak, pertimbangkan untuk Setuju. Penolakan ke-5 membuat Tim Jahat langsung menang.',
      ],
      MERLIN: [
        'Tolak tim yang berisi Tim Jahat, tapi tidak harus setiap kali.',
        'Kalau kamu selalu benar, Tim Jahat akan curiga kamu Merlin.',
        'Ingat bahwa vote semua pemain terlihat setelah voting selesai.',
      ],
      EVIL: [
        'Setujui tim yang berisi Tim Jahat, tapi jangan terlalu bersemangat.',
        'Sesekali tolak tim yang berisi temanmu supaya terlihat netral.',
        'Menolak terus-menerus juga bisa membuat Tim Jahat menang lewat 5 kali penolakan, tapi hati-hati karena itu mudah ketahuan.',
      ],
    },
    quest: {
      GOOD: ['Kamu hanya bisa memilih Sukses.', 'Setelah hasil keluar, ingat siapa saja anggota timnya.'],
      EVIL: [
        'Pilih Gagal untuk merusak misi. Kartumu anonim, hanya totalnya yang terlihat.',
        'Kamu juga boleh memilih Sukses untuk menyamar sebagai Tim Baik dan membangun kepercayaan, terutama di misi awal.',
        'Kalau ada 2 Tim Jahat di misi yang sama, sepakati siapa yang memilih Gagal. Dua kartu Gagal langsung membuka kedok kalian.',
        'Ingat bahwa misi bertanda ★ butuh 2 kartu Gagal untuk gagal.',
      ],
    },
    merlin: {
      EVIL: [
        'Siapa yang sering benar soal siapa yang jahat?',
        'Siapa yang selalu menolak tim berisi Tim Jahat?',
        'Diskusikan dulu dengan timmu sebelum memilih.',
      ],
      GOOD: ['Tetap tenang dan jangan menatap Merlin!'],
    },
  },
  help: {
    title: 'Cara Bermain',
    showTips: 'Tampilkan tips saat bermain',
    sections: [
      {
        title: 'Cara menang',
        items: [
          'Tim Baik menang dengan 3 misi sukses.',
          'Tim Jahat menang dengan 3 misi gagal, 5 kali penolakan tim dalam satu ronde, atau menebak Merlin dengan benar.',
        ],
      },
      {
        title: 'Alur tiap ronde',
        items: ['Pemimpin memilih tim → semua voting → tim menjalankan misi → giliran pemimpin pindah.'],
      },
      {
        title: 'Papan',
        items: [
          'Penghitung penolakan: kalau mencapai 5, Tim Jahat menang.',
          '★: misi ini butuh 2 kartu Gagal untuk gagal.',
        ],
      },
    ],
  },
  host: {
    title: 'Avalon Host',
    joinAt: 'Pemain bergabung di {url}',
    logout: 'Keluar',
    logoutConfirm: 'Keluar dari dashboard host?',
    tabHost: 'Kontrol host',
    tabPlay: 'Permainanku',
    lobby: 'Lobi',
    start: 'Mulai permainan dengan {n} pemain',
    needMore: 'Menunggu {n} pemain lagi.',
    tooMany: 'Terlalu banyak pemain (maks. 10).',
    kickConfirm: 'Keluarkan {name} dari lobi?',
    abortConfirm: 'Akhiri permainan ini untuk semua orang? Semua peran akan dibuka.',
    newGame: 'Permainan baru dengan pemain yang sama',
    newEmpty: 'Permainan baru (lobi kosong)',
    newEmptyConfirm: 'Keluarkan semua pemain dan buka lobi kosong? Semua orang harus bergabung lagi.',
    joined: 'Pemain yang bergabung',
    danger: 'Zona berbahaya',
    endNow: 'Akhiri permainan sekarang',
    playToo: 'Ikut bermain?',
    playerName: 'Nama pemainmu',
    join: 'Gabung',
    fairHint: 'Dashboard host tidak pernah menampilkan peran rahasia, jadi kamu tetap bisa bermain dengan adil.',
    rulesTitle: 'Aturan per jumlah pemain',
    colPlayers: 'Pemain',
    colGood: 'Baik',
    colEvil: 'Jahat',
    colQ: 'M{n}',
    star: '★ butuh 2 kartu Gagal untuk gagal.',
    recent: 'Permainan terakhir ({n})',
    goodWon: 'Tim Baik menang',
    evilWon: 'Tim Jahat menang',
    noWinner: 'Tanpa pemenang',
    inProgress: 'Sedang berjalan',
    reasons: {
      '5_rejections': '5 penolakan',
      '3_quests_failed': '3 misi gagal',
      merlin_found: 'Merlin ditemukan',
      merlin_safe: 'Merlin selamat',
      aborted: 'Dihentikan host',
    },
  },
  // Server and network messages arrive in English; these translate them.
  errors: {
    exact: {
      'Wrong password.': 'Kata sandi salah.',
      'Wrong host password.': 'Kata sandi host salah.',
      'Please enter a name.': 'Masukkan nama.',
      'That name is taken.': 'Nama itu sudah dipakai.',
      'That name is already in use by a connected player.': 'Nama itu sedang dipakai pemain yang terhubung.',
      'A game is in progress. Wait for the host to finish it, or rejoin with your previous name.':
        'Permainan sedang berlangsung. Tunggu host menyelesaikannya, atau gabung lagi dengan nama yang kamu pakai sebelumnya.',
      'Cannot reach the server.': 'Tidak bisa terhubung ke server.',
      'Not connected to the server. Reconnecting…': 'Tidak terhubung ke server. Menghubungkan ulang…',
      'The server did not respond. Try again.': 'Server tidak merespons. Coba lagi.',
      'Something went wrong.': 'Terjadi kesalahan.',
      'Your session is no longer valid. Please log in again.': 'Sesimu sudah tidak berlaku. Silakan masuk lagi.',
      'You were removed from the lobby by the host.': 'Kamu dikeluarkan dari lobi oleh host.',
      'You left the lobby.': 'Kamu keluar dari lobi.',
      'The host started a new, empty lobby. Join again to play.': 'Host membuka lobi baru yang kosong. Gabung lagi untuk bermain.',
      'That action is not available right now.': 'Aksi itu tidak tersedia sekarang.',
      'Only the host can do that.': 'Hanya host yang bisa melakukannya.',
      'You are not in this game.': 'Kamu tidak ada di permainan ini.',
      'Only the leader can propose a team.': 'Hanya pemimpin yang bisa mengusulkan tim.',
      'Unknown player in team.': 'Ada pemain tak dikenal di tim.',
      'You are not on this quest.': 'Kamu tidak ikut misi ini.',
      'You already played your card.': 'Kamu sudah memainkan kartumu.',
      'Loyal servants of Arthur must play Success.': 'Pelayan setia Arthur harus memilih Sukses.',
      'Only the Minions of Mordred choose Merlin.': 'Hanya Antek Mordred yang menebak Merlin.',
      'Pick one of the Good players.': 'Pilih salah satu pemain Tim Baik.',
      'Bad request.': 'Permintaan tidak valid.',
      'Not allowed.': 'Tidak diizinkan.',
    },
    patterns: [
      [/^Name must be at most (\d+) characters\.$/, 'Nama maksimal $1 karakter.'],
      [/^The lobby is full \((\d+) players max\)\.$/, 'Lobi sudah penuh (maks. $1 pemain).'],
      [/^Pick exactly (\d+) players for this quest\.$/, 'Pilih tepat $1 pemain untuk misi ini.'],
      [/^Avalon needs (\d+)-(\d+) players \(currently (\d+)\)\.$/, 'Avalon butuh $1-$2 pemain (sekarang $3).'],
      [/^Request failed \((\d+)\)\.$/, 'Permintaan gagal ($1).'],
    ],
  },
};

const en = {
  common: {
    loading: 'Loading…',
    connecting: 'Connecting…',
    close: 'Close',
    youParen: ' (you)',
    and: 'and',
    offline: 'Connection lost. Reconnecting…',
    yourTurn: 'Your turn',
    language: 'Language',
  },
  role: {
    GOOD: { label: 'Loyal Servant of Arthur', short: 'Good' },
    MERLIN: { label: 'Merlin', short: 'Merlin' },
    EVIL: { label: 'Minion of Mordred', short: 'Evil' },
    teamGood: 'Team Good',
    teamEvil: 'Team Evil',
    knowsMerlin: 'The Minions of Mordred are:',
    knowsEvil: 'Your fellow Minions:',
    noFellows: 'You have no fellow Minions.',
    goal: {
      GOOD: "You don't know anyone's role. Help Good succeed on 3 quests and watch who keeps failing them.",
      MERLIN: 'Guide Good without being obvious. If Evil identifies you at the end, Evil wins.',
      EVIL: 'Get onto quests and fail 3 of them. If Good wins 3 quests, your team must find Merlin.',
    },
  },
  login: {
    subtitle: 'The Resistance: Avalon. Join the table.',
    name: 'Your name',
    password: 'Game password',
    join: 'Join game',
    joining: 'Joining…',
    rejoinHint: 'Lost your session mid-game? Join again with the exact same name to get your seat back.',
    hostPassword: 'Host password',
    hostSubmit: 'Log in as host',
  },
  game: {
    playingAs: 'Playing as {name}',
    leave: 'Leave',
    leaveConfirm: 'Leave the lobby?',
    lobbyWaiting: "You're in! Waiting for the host to start the game.",
    inLobby: 'In the lobby',
    waitingNewGame: 'Waiting for the host to start a new game.',
    help: 'How to play',
  },
  lobby: {
    needs: 'Avalon needs 5 to 10 players.',
    rules: ({ n, good, evil, sizes }) =>
      `With ${n} players: ${good} Good (including Merlin) and ${evil} Evil. Quest team sizes: ${sizes}`,
  },
  board: {
    label: 'Quest board',
    q: 'Q{n}',
    doubleFail: '★ Quest 4 needs 2 Fail cards to fail',
    rejects: 'Rejected teams in a row',
    rejectsOf: '{n} of 5',
    leader: 'Leader',
    questDone: '{s} success, {f} fail',
    questSize: '{n} players',
  },
  players: {
    title: 'Players',
    online: 'Online',
    offline: 'Offline',
    leader: '♛ Leader',
    onTeam: 'On team',
    voted: 'Voted',
    voting: 'Voting…',
    played: 'Played',
    playing: 'Playing…',
    knownEvil: 'Evil (you know)',
    kick: 'Kick',
  },
  status: {
    leaderYou: 'You are the leader. Choose {size} players for Quest {q}.',
    leaderOther: '{leader} is choosing {size} players for Quest {q}.',
    voteYou: "Vote on {leader}'s team for Quest {q}.",
    waitingVotes: 'Waiting for votes from {names}.',
    questYou: 'You are on Quest {q}. Play your card.',
    questOther: 'Quest {q} in progress. Waiting for {names}.',
    merlinEvil: 'Good completed 3 quests! Discuss with your team and vote for who you think Merlin is.',
    merlinGood: 'Good completed 3 quests! Evil now tries to find Merlin…',
    voteResult: 'The vote result is in.',
    questResult: 'The result of Quest {q} is in.',
  },
  pick: {
    title: 'Choose your team',
    propose: 'Propose this team',
  },
  vote: {
    title: "{leader}'s proposed team for Quest {q}",
    approve: 'Approve',
    reject: 'Reject',
    secret: 'Your vote is secret until everyone has voted.',
    youVoted: 'You voted {choice}. You can change it until the last vote is in.',
    progress: '{done}/{total} voted. A team needs more than half the votes to be approved.',
    lastChance: 'If this team is rejected, Evil wins!',
  },
  quest: {
    title: 'Quest {q} team',
    success: 'Success',
    fail: 'Fail',
    evilHint: 'Your card is anonymous. Only the totals are revealed.',
    goodHint: 'Loyal servants of Arthur always play Success.',
    played: "You played {card}. Your card can't be changed.",
    progress: '{done}/{total} cards played.',
    needs2: 'This quest needs 2 Fail cards to fail.',
    needs1: 'One Fail card fails this quest.',
  },
  merlin: {
    title: 'Find Merlin',
    unmask: 'The Minions of Mordred reveal themselves:',
    lock: 'Talk it over with your team. The guess locks when {n} of you vote for the same player.',
    votes: ({ n }) => `${n} vote${n === 1 ? '' : 's'}`,
    goodHint: 'If Evil names Merlin correctly, Evil wins. Otherwise Good wins.',
  },
  over: {
    good: 'Good wins!',
    evil: 'Evil wins!',
    ended: 'Game ended',
    roles: "Everyone's roles",
    guess: " (Evil's guess)",
  },
  reason: {
    '5_rejections': 'Five team proposals in a row were rejected.',
    '3_quests_failed': 'Three quests failed.',
    merlin_found: 'Good completed 3 quests, but Evil found Merlin ({guess}).',
    merlin_safe: 'Good completed 3 quests. Evil guessed {guess}, but Merlin was {merlin}.',
    aborted: 'The host ended the game early.',
  },
  results: {
    title: 'Latest results',
    quest: 'Quest {q}:',
    success: 'Success',
    failed: 'Failed',
    counts: '{s} Success, {f} Fail',
    proposal: 'Quest {q}, proposal {attempt} by {leader}:',
    approved: 'Approved',
    rejected: 'Rejected',
    team: 'Team: {names}',
    history: 'All team votes ({n})',
  },
  reveal: {
    voteTitle: 'Vote result',
    questTitle: 'Quest result',
    approved: 'Team approved!',
    rejected: 'Team rejected!',
    count: '{yes} Approve · {no} Reject',
    proposedBy: "{leader}'s team for Quest {q}:",
    approvers: 'Approve',
    rejecters: 'Reject',
    nobody: 'Nobody',
    questOk: 'Quest {q} SUCCEEDED!',
    questFail: 'Quest {q} FAILED!',
    cards: '{s} Success cards · {f} Fail cards',
    teamWas: 'Quest team:',
    score: 'Score: Good {good} – Evil {evil}',
    nextQuest: 'This team goes on the quest:',
    youOnQuest: "You're on this quest! Get ready to play your card.",
    nextLeader: 'Next leader:',
    youLead: "You're the next leader! Get ready to pick a team.",
    rejectCount: 'Teams rejected in a row: {n} (max 5).',
    lastReject: 'One more rejection and Evil wins!',
    merlin: 'Good has won 3 quests! Evil will now try to find Merlin.',
    end: {
      '5_rejections': 'Five teams rejected in a row. Evil wins!',
      '3_quests_failed': 'Three quests failed. Evil wins!',
    },
    countdown: 'Continuing in {s}s',
    skip: 'Skip the pause',
  },
  roleCard: {
    tapToShow: 'Tap to reveal your secret role',
    yourRole: 'Your secret role',
    show: 'Show',
    hide: 'Hide',
  },
  roleReveal: {
    started: 'The game has started!',
    private: 'Make sure nobody else can see your screen.',
    show: 'Show my role',
    youAre: 'You are',
    tipsTitle: 'How to play this role',
    done: 'Got it, start playing',
  },
  turn: {
    pick: 'Pick a team',
    vote: 'Vote on the team',
    quest: 'Play your quest card',
    merlin: 'Find Merlin',
    result: 'See the result',
  },
  modal: {
    pick: 'Pick a team',
    vote: 'Team vote',
    quest: 'Quest',
    merlin: 'Find Merlin',
  },
  tips: {
    title: '💡 Tips',
    hide: 'Hide tips',
    role: {
      GOOD: [
        "You don't know anyone's role, so watch closely.",
        'If a quest fails, someone on that team is Evil. Remember who was on it.',
        'Also notice who approved the team that failed.',
      ],
      MERLIN: [
        "You know who is Evil, but don't let it show.",
        'Nudge your friends gently instead of accusing openly.',
        'If Good wins 3 quests, Evil gets one guess at who Merlin is. If they guess right, Good loses.',
      ],
      EVIL: [
        'Pretend to be Good and join the discussion as usual.',
        "Back your fellow Evil quietly; don't look too close.",
        'Look for the player who is always "luckily right" about who is Evil. That is probably Merlin.',
      ],
    },
    leader: {
      GOOD: [
        "Put yourself on the team, since you know you're Good.",
        'Pick players who have been on successful quests.',
        'Avoid players who were on failed quests.',
      ],
      MERLIN: [
        'Put yourself and players you know are Good on the team.',
        'Now and then include someone uncertain, so your picks don\'t look too "perfect".',
        'Give a believable reason, e.g. "they were on the quest that succeeded."',
      ],
      EVIL: [
        'Include yourself or one Evil friend. One is enough to fail the quest.',
        'Fill the rest with Good players so the team looks convincing.',
        "Don't put too many Evil players on one team; it looks suspicious.",
      ],
    },
    vote: {
      GOOD: [
        'Approve teams made of players you trust.',
        'Reject teams with suspicious players.',
        'After 4 rejections, consider approving. The 5th rejection makes Evil win immediately.',
      ],
      MERLIN: [
        'Reject teams with Evil players, but not every single time.',
        'If you are always right, Evil will suspect you are Merlin.',
        "Remember everyone's votes are shown once voting ends.",
      ],
      EVIL: [
        "Approve teams with Evil players, but don't be too eager.",
        'Now and then reject a team with your friend on it to look neutral.',
        'Rejecting over and over can win through 5 rejections, but careful: it is easy to spot.',
      ],
    },
    quest: {
      GOOD: ['You can only play Success.', 'When the result is in, remember who was on the team.'],
      EVIL: [
        'Play Fail to sabotage the quest. Your card is anonymous; only totals are shown.',
        'You can also play Success to pass as Good and build trust, especially on early quests.',
        'If 2 Evil players are on the same quest, agree on who plays Fail. Two Fail cards expose you both.',
        'Quests marked ★ need 2 Fail cards to fail.',
      ],
    },
    merlin: {
      EVIL: [
        'Who was often right about who is Evil?',
        'Who always rejected teams with Evil players?',
        'Discuss with your team before you vote.',
      ],
      GOOD: ["Stay calm and don't look at Merlin!"],
    },
  },
  help: {
    title: 'How to play',
    showTips: 'Show tips while playing',
    sections: [
      {
        title: 'How to win',
        items: [
          'Good wins with 3 successful quests.',
          'Evil wins with 3 failed quests, 5 rejected teams in one round, or by guessing Merlin correctly.',
        ],
      },
      {
        title: 'Each round',
        items: ['The leader picks a team → everyone votes → the team goes on the quest → the next player leads.'],
      },
      {
        title: 'The board',
        items: ['Rejection counter: if it reaches 5, Evil wins.', '★: this quest needs 2 Fail cards to fail.'],
      },
    ],
  },
  host: {
    title: 'Avalon Host',
    joinAt: 'Players join at {url}',
    logout: 'Log out',
    logoutConfirm: 'Log out of the host dashboard?',
    tabHost: 'Host controls',
    tabPlay: 'My game',
    lobby: 'Lobby',
    start: ({ n }) => `Start game with ${n} player${n === 1 ? '' : 's'}`,
    needMore: ({ n }) => `Waiting for ${n} more player${n === 1 ? '' : 's'}.`,
    tooMany: 'Too many players (max 10).',
    kickConfirm: 'Remove {name} from the lobby?',
    abortConfirm: 'End the current game for everyone? Roles will be revealed.',
    newGame: 'New game with the same players',
    newEmpty: 'New game (empty lobby)',
    newEmptyConfirm: 'Remove every player and open an empty lobby? Everyone will need to join again.',
    joined: 'Joined players',
    danger: 'Danger zone',
    endNow: 'End game now',
    playToo: 'Play as well?',
    playerName: 'Your player name',
    join: 'Join',
    fairHint: 'The host dashboard never shows secret roles, so you can play fairly.',
    rulesTitle: 'Rules by player count',
    colPlayers: 'Players',
    colGood: 'Good',
    colEvil: 'Evil',
    colQ: 'Q{n}',
    star: '★ needs 2 Fail cards to fail.',
    recent: 'Recent games ({n})',
    goodWon: 'Good won',
    evilWon: 'Evil won',
    noWinner: 'No winner',
    inProgress: 'In progress',
    reasons: {
      '5_rejections': '5 rejections',
      '3_quests_failed': '3 quests failed',
      merlin_found: 'Merlin found',
      merlin_safe: 'Merlin safe',
      aborted: 'Ended by host',
    },
  },
  errors: { exact: {}, patterns: [] },
};

export const STRINGS = { id, en };
export const LANGS = [
  { code: 'id', label: 'ID' },
  { code: 'en', label: 'EN' },
];
export const DEFAULT_LANG = 'id';
